FROM golang:1.10-alpine AS builder

WORKDIR /go/src/github.com/alileza/tomato

COPY . ./

RUN apk add --update make git
RUN make build-test

# ---

FROM alpine

COPY --from=builder /go/src/github.com/alileza/tomato/bin/tomato.test /bin/tomato
COPY --from=builder /go/src/github.com/alileza/tomato/examples/ /

ENTRYPOINT  [ "/bin/tomato" ]
CMD         [ "-test.run=^TestMain$", \
              "-test.coverprofile=/tmp/coverage.out", \
              "--config.file=/config.yml", \
              "--features.path=/features/" ]
