FROM golang:1.10-alpine AS builder

WORKDIR /go/src/github.com/tomatool/tomato

COPY . ./

RUN apk add --update make git
RUN make build

# ---

FROM alpine

COPY --from=builder /go/src/github.com/tomatool/tomato/bin/tomato /bin/tomato
COPY --from=builder /go/src/github.com/tomatool/tomato/examples/ /

ENTRYPOINT  [ "/bin/tomato" ]
CMD         [ "--config.file=/config.yml", \
              "--features.path=/features/" ]
